<?php

/**
 * Model_ORM_BannerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_ORM_BannerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_ORM_BannerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_ORM_Banner');
    }

    public static function getAll()
    {
        $query = Doctrine_Query::create()
                ->from('Model_ORM_Banner')
                ->orderBy('created_at DESC')
                ->setHydrationMode(Doctrine_core::HYDRATE_ARRAY);

        $banners = $query->execute();

        return $banners;
    }

    /**
     * @param array $params
     */
    public static function store($params)
    {
        $newBanner = new Model_ORM_Banner();
        $newBanner->fromArray($params);
        $newBanner->save();

    }
}